language: "node_js"
addons:
  code_climate:
    repo_token: 2f36c0162937065b43fd33d9a1e576e7b840cf214873d25ba5ba8c32a93656db
node_js:
  - "5"
  - "4"
  - "3" # io.js
  - "2" # io.js
  - "1" # io.js
  - "0.12"
  - "0.10"

after_success:
  - npm run coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  